### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by wojiaotreaty** [wojiaotreaty/CSC207_Project#2]

**Comment by skrtsamjang** [comment]
user logs in using their google account. -> access to their own google calendar

**Comment by skrtsamjang** [comment]
This issue now also takes care of initial signup case that is referred from week5ca coding
-
No longer logging in with a google account, as there were no way to obtain and use api externally outside of google's verification of the app

**Comment by skrtsamjang** [comment]
Final description of the issue:
This is a signup and login implementation that is similar to week5ca coding, except when app first opens, it opens up login screen before signup screen. When the login is successful, the interactor will pass on all of the User's informatio to the dashboard implementation.
