### ISSUE TITLE
Delete Project Use Case Implementation

### ISSUE THREAD

**Issue by wojiaotreaty** [wojiaotreaty/CSC207_Project#5]
Implement a delete project use case which allows the user to delete a project that they own. When project view (#14) activates delete project, the corresponding project id is input and used to delete the Project from the User's projects. This change is then saved (#15). Finally, the project name and project id are output.

**Comment by bing-j** [comment]
TODO: modify presenter & factory to accomodate for switching views after the project is deleted (should go from project view #14 to dashboard view #13 )

**Comment by bing-j** [comment]
TODO: modify presenter to change DashboardState (#13) by removing the ProjectData that represents the deleted project from the state
